printWidth: 200
useTabs: true
tabWidth: 2
semi: true
singleQuote: true
quoteProps: 'as-needed'
trailingComma: 'all'
bracketSpacing: true
bracketSameLine: false
arrowParens: 'always'
endOfLine: 'crlf'
jsxBracketSameLine: true
